### ISSUE TITLE
Expand/Collapse Facet panel

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-arranger#75]
Add the ability to change the size, or collapse the left facet panel. 

As examples:
- HCMI has the abiltiy to expand (https://hcmi.netlify.com/) 
- GDC has the ability to collapse (https://portal.gdc.cancer.gov/exploration) 

Mockup:
Similar to HCMI, the crosshair icon will show up when the user hovers over the edges of the panels (both facet and action panels).
The title area of the facet panel will change slightly to match the collapsible style of the action panel.
![06 kf-file-repo-expandable-facet-panel](https://user-images.githubusercontent.com/18424138/46107752-373ac680-c1aa-11e8-8fe2-5e0f6e260674.jpg)

**Comment by kcullion** [comment]
@rosibaj if we allow the user to adjust the size of the facet panel, should we allow that with the actions panel too? So both panels will be adjustable/collapsable

**Comment by rosibaj** [comment]
@kcullion that seems reasonable!

**Comment by kcullion** [comment]
@rosibaj are we still going to change "ALL FILTERS" to "BROWSE ALL"?

**Comment by rosibaj** [comment]
@kcullion yes, i think so.  We can make a separate ticket for just a text change though!

**Comment by rosibaj** [comment]
Linked to: https://github.com/kids-first/kf-portal-ui/issues/814 (possibly may move to UI only implementation)

**Comment by rosibaj** [comment]
changed to a portal-ui ticket; closing as a duplicate.
